[ 2024-12-01 16:08:00,046 ] 1038 INFO HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2024-12-01 16:08:00,062 ] 107 INFO Accessing as mshivakumarreddy78
[ 2024-12-01 16:08:04,170 ] 1038 INFO HTTP Request: GET https://dagshub.com/api/v1/repos/mshivakumarreddy78/MLOPSPRACTICE "HTTP/1.1 200 OK"
[ 2024-12-01 16:08:07,369 ] 1038 INFO HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2024-12-01 16:08:07,369 ] 107 INFO Initialized MLflow to track repo "mshivakumarreddy78/MLOPSPRACTICE"
[ 2024-12-01 16:08:07,385 ] 107 INFO Repository mshivakumarreddy78/MLOPSPRACTICE initialized!
[ 2024-12-01 16:10:33,748 ] 32 INFO number of columns in schema file 2
[ 2024-12-01 16:10:33,748 ] 33 INFO number of columns in dataframe 31
[ 2024-12-01 16:10:33,748 ] 32 INFO number of columns in schema file 2
[ 2024-12-01 16:10:33,748 ] 33 INFO number of columns in dataframe 31
[ 2024-12-01 16:10:38,872 ] 870 WARNING Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023DD3A97AC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2024-12-01 16:10:46,988 ] 870 WARNING Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023DD3A97E80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2024-12-01 16:10:59,385 ] 870 WARNING Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023DD3AE09A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2024-12-01 16:11:19,462 ] 870 WARNING Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023DD3AE0910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2024-12-01 16:11:55,714 ] 870 WARNING Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023DD3AE1720>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
